// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import { navs } from "@/constants";
import { BilibiliOutlined, GithubOutlined, XOutlined } from "@ant-design/icons";
import Link from "next/link";
import "tailwindcss/tailwind.css";
import styles from "./index.module.scss";

const socialMedias = [
  <GithubOutlined key="github" />,
  <XOutlined key="x" />,
  <BilibiliOutlined key="bilibili" />,
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <div className={styles.nav}>
          <h1 className="text-3xl">zhchENG</h1>
          <ul className="flex gap-x-8">
            {navs.map((nav) => (
              <Link key={nav} href="/" className=" text-lg">
                {nav}
              </Link>
            ))}
          </ul>
          <ul className="flex gap-x-4 text-xl">
            {socialMedias.map((Media, idx) => (
              <Link key={idx} href="/">
                {Media}
              </Link>
            ))}
          </ul>
        </div>
        {children}
      </body>
    </html>
  );
}
